apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx-prod
  namespace: argocd
spec:
  project: argocd-gitops-lab
  source:
    repoURL: https://github.com/SalesFX/argocd-gitops-lab
    targetRevision: HEAD
    path: prod/app
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
